---
title: "Alpha and Beta Diversity, MS5"
author: "Ioannis D. Kampouris"
date: "2025-02-11"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Load the packages
```{r}
library(tidyverse)
library(ggplot2)
library(plyr)
library(dplyr)
library(readr)
library(readxl)
library(ggpubr)
library(stringi)
library(tidyr)
library(reshape2)
library(vegan)
library(parallel)
```
Load the metadata
```{r}
metadata1=read.csv("metadata1.csv")

```

Load the tables of Diversity
```{r}
Taxonomy=read.csv("ASV_Table_LTE_three_years.csv", row.names = "X")
Taxonomy=Taxonomy[1:3,c(1:7,ncol(Taxonomy))]
rownames(Taxonomy)=Taxonomy$ASV
Rarefied_Table1=read.csv(file = "3yearsRarefied_table.csv",row.names = "X")
```

First Compare the alpha Diversity metrics in Rhizosphere
```{r}
for(i in c(20,21,22) ){
metadata_RH=filter(metadata1, Soil_Type=="RH"&Year==paste0(i))
Rarefied_Table_RH=Rarefied_Table1[metadata_RH$Sample,]
dist1=vegdist(log10(Rarefied_Table_RH[metadata_RH$Sample,]+1), method = "bray")
dist1b=cmdscale(dist1, k=2, eig=T)
dist1c=scores(dist1b, display = "sites")
dist1d=cbind(dist1c[metadata_RH$Sample,], metadata_RH)

mdsplots1= ggplot(dist1d,aes(x=Dim1, y=Dim2, fill=(BM) ))+
  geom_point(shape=21,  size=10)+
  #scale_shape_manual(name="Sampling Year",values = c(21,22,23))+
   theme_bw()+
  theme( strip.background = element_rect( fill="white", colour="white")) +
  theme( strip.text =  element_text( colour="black", face="bold.italic", size=25)) +
  ggtitle(paste( "Rhizosphere", "Year", i))+
  scale_fill_manual(name="",values=c( "#ff9900","#146eb4"))+

  theme(axis.text = element_text(size = 25, face = "bold", colour="black")) +
  theme(legend.text = element_text( size=25, face="bold", colour = "black")) + 
      theme(plot.title = element_text( size=35, face="bold", colour = "black")) + 

    theme(legend.title = element_text( size=35, face="bold", colour = "black")) + 
  
  theme(legend.position = "right",
        axis.title.y = element_text( size=25, face = "bold", colour="black")) + 
  theme(axis.title.x = element_text(size = 25, face = "bold", colour="black"))+
  xlab(paste0("MDS1[",round((100*dist1b$eig[1]/sum(dist1b$eig)),2),"%]"))+
  ylab(paste0("MDS2[",round((100*dist1b$eig[2]/sum(dist1b$eig)),2),"%]"))


ggsave(mdsplots1,file = paste0("Year ",i, " Beta.RH.pdf"),
       height = 8, width = 8)

permanova1=adonis2(dist1~BM, data=dist1d, by="terms", permutations = 9999)
write.csv( as.data.frame( permanova1), file = paste0("Year ",i, 
" PERMANOVA.RH.csv"))
}
```

```{r}
ggsave(Diversity_plot_RH,file = "Alpha.RH.pdf", height = 8, width = 20)

```

Second Compare the alpha Diversity metrics in Root Associated soil (RAS)
```{r}
for(i in c(20,21,22) ){
metadata_RAS=filter(metadata1, Soil_Type=="RAS"&Year==paste0(i))
Rarefied_Table_RAS=Rarefied_Table1[metadata_RAS$Sample,]
dist1=vegdist(log10(Rarefied_Table_RAS[metadata_RAS$Sample,]+1), method = "bray")
dist1b=cmdscale(dist1, k=2, eig=T)
dist1c=scores(dist1b, display = "sites")
dist1d=cbind(dist1c[metadata_RAS$Sample,], metadata_RAS)

mdsplots1= ggplot(dist1d,aes(x=Dim1, y=Dim2, fill=(BM) ))+
  geom_point(shape=21,  size=10)+
  #scale_shape_manual(name="Sampling Year",values = c(21,22,23))+
   theme_bw()+
  theme( strip.background = element_rect( fill="white", colour="white")) +
  theme( strip.text =  element_text( colour="black", face="bold.italic", size=25)) +
  ggtitle(paste( "RASizosphere", "Year", i))+
  scale_fill_manual(name="",values=c( "#ff9900","#146eb4"))+

  theme(axis.text = element_text(size = 25, face = "bold", colour="black")) +
  theme(legend.text = element_text( size=25, face="bold", colour = "black")) + 
      theme(plot.title = element_text( size=35, face="bold", colour = "black")) + 

    theme(legend.title = element_text( size=35, face="bold", colour = "black")) + 
  
  theme(legend.position = "right",
        axis.title.y = element_text( size=25, face = "bold", colour="black")) + 
  theme(axis.title.x = element_text(size = 25, face = "bold", colour="black"))+
  xlab(paste0("MDS1[",round((100*dist1b$eig[1]/sum(dist1b$eig)),2),"%]"))+
  ylab(paste0("MDS2[",round((100*dist1b$eig[2]/sum(dist1b$eig)),2),"%]"))


ggsave(mdsplots1,file = paste0("Year ",i, " Beta.RAS.pdf"),
       height = 8, width = 8)

permanova1=adonis2(dist1~BM, data=dist1d, by="terms", permutations = 9999)
write.csv( as.data.frame( permanova1), file = paste0("Year ",i, 
" PERMANOVA.RAS.csv"))
}
```

Third Compare the Yearly alpha Diversity metrics in Bulk Soil T0
```{r}
metadata_T0=filter(metadata1, Soil_Type=="T0")
Rarefied_Table_T0=Rarefied_Table1[metadata_T0$Sample,]
dist1=vegdist(log10(Rarefied_Table_T0[metadata_T0$Sample,]+1), method = "bray")
dist1b=cmdscale(dist1, k=2, eig=T)
dist1c=scores(dist1b, display = "sites")
dist1d=cbind(dist1c[metadata_T0$Sample,], metadata_T0)

mdsplots1= ggplot(dist1d,aes(x=Dim1, y=Dim2, fill=as.factor(Year) ))+
  geom_point(shape=21,  size=10)+
  #scale_shape_manual(name="Sampling Year",values = c(21,22,23))+
   theme_bw()+
  theme( strip.background = element_rect( fill="white", colour="white")) +
  theme( strip.text =  element_text( colour="black", face="bold.italic", size=25)) +
  ggtitle(paste( "T0izosphere"))+
  scale_fill_brewer(name="",palette = "Set3" )+

  theme(axis.text = element_text(size = 25, face = "bold", colour="black")) +
  theme(legend.text = element_text( size=25, face="bold", colour = "black")) + 
      theme(plot.title = element_text( size=35, face="bold", colour = "black")) + 

    theme(legend.title = element_text( size=35, face="bold", colour = "black")) + 
  
  theme(legend.position = "right",
        axis.title.y = element_text( size=25, face = "bold", colour="black")) + 
  theme(axis.title.x = element_text(size = 25, face = "bold", colour="black"))+
  xlab(paste0("MDS1[",round((100*dist1b$eig[1]/sum(dist1b$eig)),2),"%]"))+
  ylab(paste0("MDS2[",round((100*dist1b$eig[2]/sum(dist1b$eig)),2),"%]"))


ggsave(mdsplots1,file = paste0( "Beta.T0.pdf"),
       height = 8, width = 8)

permanova1=adonis2(dist1~Year, data=dist1d, by="terms", permutations = 9999)
write.csv( as.data.frame( permanova1), file = " PERMANOVA.T0.csv")

```

```{r}
```
