---
title: "Alpha and Beta Diversity, MS5"
author: "Ioannis D. Kampouris"
date: "2025-02-11"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



Load the packages
```{r}
library(tidyverse)
library(ggplot2)
library(plyr)
library(dplyr)
library(readr)
library(readxl)
library(ggpubr)
library(stringi)
library(tidyr)
library(reshape2)
library(vegan)
library(parallel)
```
Load the metadata
```{r}
metadata1=read.csv("metadata1.csv")

```

Load the tables of Diversity
```{r}
Rarefied_Richness=read.csv(file = "3yearsGERarefied_Richness.csv",row.names = "X")
Rarefied_Shannon=read.csv(file = "3yearsRarefied_Shannon.csv",row.names = "X")
Rarefied_simpson=read.csv(file = "3yearsRarefied_simpson.csv",row.names = "X")
all_diversities=cbind(metadata1, Richness=Rarefied_Richness[metadata1$Sample,],
Shannon_Index=Rarefied_Shannon[metadata1$Sample,],
Reverse_Simpson_Index=1/Rarefied_Shannon[metadata1$Sample,])%>%
  mutate(Evenness=Shannon_Index/log(Richness))%>%
  gather(-c(colnames(metadata1)), key="Index", value="Value" )
all_diversities$Index2=factor(
  all_diversities$Index
  ,c(
"Richness",
"Reverse_Simpson_Index" ,
"Shannon_Index",
"Evenness"
))
```
First Compare the alpha Diversity metrics in Rhizosphere
```{r}
all_diversities_RH=filter(all_diversities, Soil_Type=="RH")
Diversity_plot_RH=ggplot(all_diversities_RH, aes(x=as.factor(Year), 
y=Value, fill=BM))+
  theme_bw()+
  geom_pointrange(stat = "summary",
position = position_dodge2(width = 0.5), shape=21, size=2)+
  facet_wrap(~Index2, scales ="free", strip.position="left",
             nrow = 1)+
  theme( strip.background = element_rect( fill="white", colour="white")) +
  theme( strip.text =  element_text( colour="black", face="bold", size=35),
         strip.placement = "outside") +
  ylab("")+xlab("")+ggtitle("Rhizosphere")+
    scale_fill_manual(name="",values=c( "#ff9900","#146eb4"))+

  theme(axis.text = element_text(size = 35, face = "bold", colour="black")) +
  theme(legend.text = element_text( size=35, face="bold", colour = "black")) + 
  theme(legend.title = element_text( size=35, face="bold", colour = "black")) + 
    theme(legend.position = "top",
        axis.title.y = element_text( size=35, face = "bold", colour="black")) + 
  theme(axis.title.x = element_text(size = 35, face = "bold", colour="black"))+
  stat_compare_means(method = "wilcox.test", label = "p.signif")

```

```{r}
ggsave(Diversity_plot_RH,file = "Alpha.RH.pdf", height = 8, width = 20)

```

Second Compare the alpha Diversity metrics in Root Associated soil (RAS)
```{r}
all_diversities_RAS=filter(all_diversities, Soil_Type=="RAS")
diversity_plot_RAS=ggplot(all_diversities_RAS, aes(x=as.factor(Year), 
                                        y=Value, fill=BM))+theme_bw()+
  geom_pointrange(stat = "summary",
position = position_dodge2(width = 0.5), shape=21, size=2)+
  facet_wrap(~Index2, scales ="free", strip.position="left",
             nrow = 1)+
  theme( strip.background = element_rect( fill="white", colour="white")) +
  theme( strip.text =  element_text( colour="black", face="bold", size=35),
         strip.placement = "outside") +
  ylab("")+xlab("")+ggtitle("RAS")+
    scale_fill_manual(name="",values=c( "#ff9900","#146eb4"))+

  theme(axis.text = element_text(size = 35, face = "bold", colour="black")) +
  theme(legend.text = element_text( size=35, face="bold", colour = "black")) + 
  theme(legend.title = element_text( size=35, face="bold", colour = "black")) + 
    theme(legend.position = "top",
        axis.title.y = element_text( size=35, face = "bold", colour="black")) + 
  theme(axis.title.x = element_text(size = 35, face = "bold", colour="black"))+
  stat_compare_means(method = "wilcox.test", label = "p.signif")
```

```{r}
ggsave(diversity_plot_RAS,file = "Alpha.RAS.pdf", height = 8, width = 20)

```

Third Compare the Yearly alpha Diversity metrics in Bulk Soil T0
```{r}
all_diversities_T0=filter(all_diversities, Soil_Type=="T0")
diversity_plot_T0=ggplot(all_diversities_T0, aes(x=as.factor(Year), 
                                        y=Value, fill=as.factor(Year)))+
  geom_pointrange(stat = "summary",
position = position_dodge2(width = 0.5), shape=21, size=2)+
  scale_fill_brewer(palette = "Set3", name="")+
  facet_wrap(~Index2, scales ="free", strip.position="left",
             nrow = 1)+theme_bw()+
  theme( strip.background = element_rect( fill="white", colour="white")) +
  theme( strip.text =  element_text( colour="black", face="bold", size=35),
         strip.placement = "outside") +
  ylab("")+xlab("Year")+ggtitle("BS T0")+

  theme(axis.text = element_text(size = 35, face = "bold", colour="black")) +
  theme(legend.text = element_text( size=35, face="bold", colour = "black")) + 
  theme(legend.title = element_text( size=35, face="bold", colour = "black")) + 
    theme(legend.position = "top",
        axis.title.y = element_text( size=35, face = "bold", colour="black")) + 
  theme(axis.title.x = element_text(size = 35, face = "bold", colour="black"))+
  stat_pwc(label = "p.adj")
```

```{r}
ggsave(diversity_plot_T0,file = "Alpha.T0.pdf", height = 8, width = 20)
```

```{r}
```
