---
title: "Alpha and Beta Diversity, MS5"
author: "Ioannis D. Kampouris"
date: "2025-02-11"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Load the packages
```{r}
library(tidyverse)
library(ggplot2)
library(plyr)
library(dplyr)
library(readr)
library(readxl)
library(ggpubr)
library(stringi)
library(tidyr)
library(reshape2)
library(vegan)
library(parallel)
```
Load the metadata
```{r}
metadata1=read.csv("metadata1.csv")

```

Load the tables of Diversity
```{r}
Taxonomy=read.csv("ASV_Table_LTE_three_years.csv", row.names = "X")
Taxonomy=Taxonomy[,c(1:7,ncol(Taxonomy))]
rownames(Taxonomy)=Taxonomy$ASV
Rarefied_Table1=read.csv(file = "3yearsRarefied_table.csv",row.names = "X")
```

First Compare the alpha Diversity metrics in Rhizosphere
```{r}
metadata_RH=filter(metadata1, Soil_Type=="RH")
multiple_glms_ASVs_df_list=list()
for(i in unique(metadata_RH$Year)){

file1=filter( metadata_RH, Year==i)
multiple_glm= function(x){
  
  file1$Treatment2=file1$BM
  file1$Treatment2[file1$Treatment2=="BMc"]<-1
  file1$Treatment2[file1$Treatment2=="Control"]<-0
  file1$Treatment2=as.numeric(  file1$Treatment2)
  if(sum(x[x>0])>3){
    
   Table_glm=glm(file1$Treatment2~scale(log10(x+1)), family=binomial(link="logit"))
    file2=anova(Table_glm, test = "Chisq")
    FC1=dcast(data.frame(T=file1$BM, A=x), T~., value.var = "A",  mean)
    
    FC2=log2((FC1[1,2]+1)/(FC1[2,2]+1))
    
    file3=data.frame(coeff=(Table_glm$coefficients[2]), p=file2$`Pr(>Chi)`[2],  FC=FC2, Mean=mean(x))
    
    return(file3)
  
}}

multiple_glms_ASVs= apply(Rarefied_Table1[file1$Sample,],2, 
function(x) multiple_glm(x))
multiple_glms_ASVs_df <- as.data.frame(do.call(rbind, multiple_glms_ASVs))
multiple_glms_ASVs_df[is.na(multiple_glms_ASVs_df)]<-1
multiple_glms_ASVs_df$padj=p.adjust(multiple_glms_ASVs_df$p, method="BH")
multiple_glms_ASVs_df=filter(multiple_glms_ASVs_df)%>%mutate(
  Year=unique(file1$Year))%>%rownames_to_column(var="ASV")

multiple_glms_ASVs_df_list=rbind(multiple_glms_ASVs_df_list,
                                 multiple_glms_ASVs_df)

}

multiple_glms_ASVs_df_list2=filter(multiple_glms_ASVs_df_list, padj<0.05)
multiple_glms_ASVs_df_list3=full_join(Taxonomy,multiple_glms_ASVs_df_list2)%>%filter(FC!="NA")
 multiple_glms_ASVs_df_list3$tax.Genus[is.na( multiple_glms_ASVs_df_list3$tax.Genus)]="Unclassified"
write.csv(rename( multiple_glms_ASVs_df_list3, "log2FC"="FC"),
          "Differential_Abundance_Table_ASVs_with_Full_taxonomy.csv")
 
```
```{r}
plot1= ggplot(multiple_glms_ASVs_df_list3, 
aes(x=(100*Mean/unique (rowSums(Rarefied_Table1))), y=FC, fill=paste0(tax.Phylum)))+
  facet_wrap(~paste0("20", Year), scales = "fixed", nrow=1)+
  geom_point( size=6, shape=21, colour="black")+
  scale_shape_manual(values = c(21,22,23), name="")+
  ylab("Log2FC(BMc/Ctrl)")+xlab("Mean Relative Abundance (%)") + 
  scale_fill_brewer(palette = "Paired", name="Genus")  +
  theme_bw() +
  
  theme( axis.text.y = element_text( size=40, face = "bold", colour="black")) +
  theme(axis.text.x = element_text(size = 40, face = "bold", colour="black")) +
  theme(legend.text = element_text( size=40, face="italic", colour = "black")) + 
  theme( axis.title.y = element_text( size=40, face = "bold", colour="black")) + 
  theme(axis.title.x = element_text(size = 40, face = "bold", colour="black")) +
  theme(legend.title =  element_text( size=40, face="bold", colour = "black"))+
  theme(plot.title =  element_text( size=40, face="bold", colour = "black"))+
  
  theme( strip.text = element_text( size=40, face = "bold", colour="white")) +
  theme( strip.background = element_rect( fill="skyblue4")) +
  theme(legend.position="right") + theme( axis.line = element_line(colour = "black", 
                                                                   size = 2, linetype = "solid"))+ 
  guides(fill = guide_legend(override.aes = list(shape = 21, size=10)))+ 
  guides(colour = guide_legend(override.aes = list(linewidth = 0)))+
  guides(shape = guide_legend(override.aes = list(size=14))) +
scale_fill_brewer(palette = "Paired", name="")+
  ggtitle("Differential abundance of bacterial ASVs")

png(filename = "Diff_abundance.png", width = 9000, res=300, height = 2500)
print(plot1)
dev.off()

```


```{r}
ggsave(plot1,file = "Diff_Abundance.RH.pdf", height = 8, width = 30)

```




```{r}
metadata_RAS=filter(metadata1, Soil_Type=="RAS")
multiple_glms_ASVs_df_list=list()
for(i in unique(metadata_RAS$Year)){

file1=filter( metadata_RAS, Year==i)
multiple_glm= function(x){
  
  file1$Treatment2=file1$BM
  file1$Treatment2[file1$Treatment2=="BMc"]<-1
  file1$Treatment2[file1$Treatment2=="Control"]<-0
  file1$Treatment2=as.numeric(  file1$Treatment2)
  if(sum(x[x>0])>3){
    
   Table_glm=glm(file1$Treatment2~scale(log10(x+1)), family=binomial(link="logit"))
    file2=anova(Table_glm, test = "Chisq")
    FC1=dcast(data.frame(T=file1$BM, A=x), T~., value.var = "A",  mean)
    
    FC2=log2((FC1[1,2]+1)/(FC1[2,2]+1))
    
    file3=data.frame(coeff=(Table_glm$coefficients[2]), p=file2$`Pr(>Chi)`[2],  FC=FC2, Mean=mean(x))
    
    return(file3)
  
}}

multiple_glms_ASVs= apply(Rarefied_Table1[file1$Sample,],2, 
function(x) multiple_glm(x))
multiple_glms_ASVs_df <- as.data.frame(do.call(rbind, multiple_glms_ASVs))
multiple_glms_ASVs_df[is.na(multiple_glms_ASVs_df)]<-1
multiple_glms_ASVs_df$padj=p.adjust(multiple_glms_ASVs_df$p, method="BH")
multiple_glms_ASVs_df=filter(multiple_glms_ASVs_df)%>%mutate(
  Year=unique(file1$Year))%>%rownames_to_column(var="ASV")

multiple_glms_ASVs_df_list=rbind(multiple_glms_ASVs_df_list,
                                 multiple_glms_ASVs_df)

}

multiple_glms_ASVs_df_list2=filter(multiple_glms_ASVs_df_list, padj<0.05)
multiple_glms_ASVs_df_list3=full_join(Taxonomy,multiple_glms_ASVs_df_list2)%>%filter(FC!="NA")

plot1= ggplot(multiple_glms_ASVs_df_list3, 
aes(x=(100*Mean/unique (rowSums(Rarefied_Table1))), y=FC, fill=paste0(tax.Phylum)))+
  facet_wrap(~paste0("20", Year), scales = "fixed", nrow=1)+
  geom_point( size=6, shape=21, colour="black")+
  scale_shape_manual(values = c(21,22,23), name="")+
  ylab("Log2FC(BMc/Ctrl)")+xlab("Mean Relative Abundance (%)") + 
  scale_fill_brewer(palette = "Paired", name="Genus")  +
  theme_bw() +
  
  theme( axis.text.y = element_text( size=40, face = "bold", colour="black")) +
  theme(axis.text.x = element_text(size = 40, face = "bold", colour="black")) +
  theme(legend.text = element_text( size=40, face="italic", colour = "black")) + 
  theme( axis.title.y = element_text( size=40, face = "bold", colour="black")) + 
  theme(axis.title.x = element_text(size = 40, face = "bold", colour="black")) +
  theme(legend.title =  element_text( size=40, face="bold", colour = "black"))+
  theme(plot.title =  element_text( size=40, face="bold", colour = "black"))+
  
  theme( strip.text = element_text( size=40, face = "bold", colour="white")) +
  theme( strip.background = element_rect( fill="skyblue4")) +
  theme(legend.position="right") + theme( axis.line = element_line(colour = "black", 
                                                                   size = 2, linetype = "solid"))+ 
  guides(fill = guide_legend(override.aes = list(shape = 21, size=10)))+ 
  guides(colour = guide_legend(override.aes = list(linewidth = 0)))+
  guides(shape = guide_legend(override.aes = list(size=14))) +
scale_fill_brewer(palette = "Paired", name="")+
  ggtitle("Differential abundance of bacterial ASVs")

png(filename = "Diff_abundance.png", width = 9000, res=300, height = 2500)
print(plot1)
dev.off()

```


```{r}
ggsave(plot1,file = "Diff_Abundance.RAS.pdf", height = 8, width = 30)
```


```{r}
agglommerate1= cbind(Taxonomy[colnames((Rarefied_Table1)), "tax.Phylum", drop=F], t(Rarefied_Table1))%>%
  as.data.frame()%>%
aggregate(.~tax.Phylum,  sum)%>%
  gather(-tax.Phylum, key="Sample", value="RA", )%>%
  full_join(metadata1)

Phylum_RH=filter(agglomrate1, Soil_Type=="RH")
Phylum_RH2=dcast(Phylum_RH, tax.Phylum~., value.var = "RA", mean)
Phylum_RH2=Phylum_RH2[order(Phylum_RH2$., decreasing = T),]
Phylum_RH2=Phylum_RH2[1:5,]
Phylum_RH3=filter(Phylum_RH, tax.Phylum%in%c(Phylum_RH2$tax.Phylum))
Phylum_RAS=filter(agglomrate1, Soil_Type=="RAS")

```


```{r}
plot_phyla= ggplot(Phylum_RH3, 
aes(y=(100*RA/unique (rowSums(Rarefied_Table1))), x=as.factor(Year),
    fill=BM))+ geom_pointrange(stat="summary",
      shape=21, size=2, position = 
position_dodge2(width=1))+facet_wrap(~tax.Phylum, nrow = 1, scales = "free")+
  theme_bw() +
  xlab("Year")+ylab("RA(%)")+
  
  theme( axis.text.y = element_text( size=40, face = "bold", colour="black")) +
  theme(axis.text.x = element_text(size = 40, face = "bold", colour="black")) +
  theme(legend.text = element_text( size=40, face="bold", colour = "black")) + 
  theme( axis.title.y = element_text( size=40, face = "bold", colour="black")) + 
  theme(axis.title.x = element_text(size = 40, face = "bold", colour="black")) +
  theme(legend.title =  element_text( size=40, face="bold", colour = "black"))+
  theme(plot.title =  element_text( size=40, face="bold", colour = "black"))+
  
  theme( strip.text = element_text( size=40, face = "bold.italic", colour="black")) +
  theme( strip.background = element_rect( fill="white", colour = "white")) +
  theme(legend.position="right") + theme( axis.line = element_line(colour = "black", 
                                                                   size = 1.5, linetype = "solid"))+ 
  stat_compare_means(method = "wilcox.test", label = "p.signif",size=10, hide.ns = T)+
    scale_fill_manual(name="",values=c( "#ff9900","#146eb4"))


```



```{r}
ggsave(plot_phyla,file = "Diff_Abundance.RH.Phyla.pdf",  height = 8, width = 30)

```

```{r}
agglommerate1= cbind(Taxonomy[colnames((Rarefied_Table1)), "tax.Phylum", drop=F], t(Rarefied_Table1))%>%
  as.data.frame()%>%
aggregate(.~tax.Phylum,  sum)%>%
  gather(-tax.Phylum, key="Sample", value="RA", )%>%
  full_join(metadata1)

Phylum_RAS=filter(agglomrate1, Soil_Type=="RAS")
Phylum_RAS2=dcast(Phylum_RAS, tax.Phylum~., value.var = "RA", mean)
Phylum_RAS2=Phylum_RAS2[order(Phylum_RAS2$., decreasing = T),]
Phylum_RAS2=Phylum_RAS2[1:5,]
Phylum_RAS3=filter(Phylum_RAS, tax.Phylum%in%c(Phylum_RAS2$tax.Phylum))
Phylum_RAS=filter(agglomrate1, Soil_Type=="RAS")

```


```{r}
plot_phyla= ggplot(Phylum_RAS3, 
aes(y=(100*RA/unique (rowSums(Rarefied_Table1))), x=as.factor(Year),
    fill=BM))+ geom_pointrange(stat="summary",
      shape=21, size=2, position = 
position_dodge2(width=1))+facet_wrap(~tax.Phylum, nrow = 1, scales = "free")+
  theme_bw() +
  xlab("Year")+ylab("RA(%)")+
  
  theme( axis.text.y = element_text( size=40, face = "bold", colour="black")) +
  theme(axis.text.x = element_text(size = 40, face = "bold", colour="black")) +
  theme(legend.text = element_text( size=40, face="bold", colour = "black")) + 
  theme( axis.title.y = element_text( size=40, face = "bold", colour="black")) + 
  theme(axis.title.x = element_text(size = 40, face = "bold", colour="black")) +
  theme(legend.title =  element_text( size=40, face="bold", colour = "black"))+
  theme(plot.title =  element_text( size=40, face="bold", colour = "black"))+
  
  theme( strip.text = element_text( size=40, face = "bold.italic", colour="black")) +
  theme( strip.background = element_rect( fill="white", colour = "white")) +
  theme(legend.position="right") + theme( axis.line = element_line(colour = "black", 
                                                                   size = 1.5, linetype = "solid"))+ 
  stat_compare_means(method = "wilcox.test", label = "p.signif",size=10, hide.ns = T)+
    scale_fill_manual(name="",values=c( "#ff9900","#146eb4"))


```


```{r}
ggsave(plot_phyla,file = "Diff_Abundance.RAS.Phyla.pdf",  height = 8, width = 35)
```


```{r}
LoadABi03=Biostrings::readDNAStringSet("type_16SrRNA_regionBacillus_newfa.fasta")

LoadABi03_B=data.frame(Seq= as.character(LoadABi03))
LoadABi03_C=rownames_to_column(var="Gene", LoadABi03_B)%>%
  mutate(Type=str_replace( Gene,"Bac_atrophaeus_", "ABi03 16S rRNA gene cloned fragment "))
LoadABi03_percentage=pwalign::pairwiseAlignment(LoadABi03_C[1,2],Taxonomy["ASV21",1], type="global")
LoadABi03_percentage2=pwalign::pid(LoadABi03_percentage)
LoadBacillusMAG=Biostrings::readDNAStringSet(
"drep_output_directory_incomplete/dereplicated_genomes/S4_SemiBin_0.fa.gz_round4_pilon_out/S4_SemiBin_0.fa.gz_round4_pilon_out.ffn"
)

LoadBacillusMAG_B=data.frame(Seq= as.character(LoadBacillusMAG))
LoadBacillusMAG_C=rownames_to_column(var="Gene", LoadBacillusMAG_B)%>%filter(str_detect(Gene,"16S ribosomal"))%>%
  mutate(Type="16S rRNA gene MAG: S4_SemiBin_0 ")
LoadBacillusMAG_C$Type=paste0(LoadBacillusMAG_C$Type," ", rownames(LoadBacillusMAG_C))
LoadBacillus=full_join(LoadBacillusMAG_C,LoadABi03_C)
LoadBacillus2=full_join(LoadBacillus, data.frame(Seq=Taxonomy["ASV21",1], Type="ASV21"))

alignments=list()
for(i in 1:nrow(LoadBacillus2)){
for(j in 1:nrow(LoadBacillus2)){
alignment1=pwalign::pairwiseAlignment(LoadBacillus2[j,2],LoadBacillus2[(i),2], type="local")
alignment2=pwalign::pid(alignment1) 
alignment3= data.frame(id=alignment2, Alignment=paste0(LoadBacillus2[j,3],"-",LoadBacillus2[(i),3]))
alignments=rbind(alignment3,alignments)
print(paste0(i))
}

}
alignments2=separate(alignments, col = Alignment, into = c("S1", "S2"), sep = "-")
alignments2$row=rownames(alignments2)
alignments3=dcast(alignments2, S1~S2, value.var = "id", mean, fill = 100)
alignments4=gather(alignments3, -c( "S1"), key="S2", value="id")
ord_mat=column_to_rownames(alignments3, var = "S1")
dist1=as.matrix((100- ord_mat)^1/2)
dist2=metaMDS(dist1, k=2, distance = "euclidean")
dist3=scores(dist2, display="sites")

plot1=ggplot(dist3, aes(x=NMDS1, 
y=NMDS2))+geom_point()+ geom_text(aes(label=rownames(dist3)))
  scale_fill_distiller(palette = "Spectral", name="Sequence Similarity (%)")+
  xlab("")+
  ylab("")+
    theme( axis.text.y = element_text( size=20, face = "bold", colour="black")) +
  theme(axis.text.x = element_text(size = 20, face = "bold",angle = 45, hjust = 1,  colour="black")) +
  theme(legend.text = element_text( size=20, face="bold", colour = "black")) + 
  theme( axis.title.y = element_text( size=20, face = "bold", colour="black")) + 
  theme(axis.title.x = element_text(size = 20, face = "bold",  colour="black")) +
  theme(legend.title =  element_text( size=20, face="bold", colour = "black"))+
  theme(plot.title =  element_text( size=20, face="bold", colour = "black"),
        legend.key.size = unit(2,"cm"),legend.position = "top")
  

```

```{r}
png(filename = "ABi03_MAG_heatmap.png", width =1500, height = 1000)
print(plot1)
dev.off()
```

```{r}
png(filename = "ABi03_MAG_heatmap.png", width =1500, height = 1000)
print(plot1)
dev.off()
```
```{r}
ASV21=cbind(metadata_RH,  Rarefied_Table1[metadata_RH$Sample, c("ASV21"), drop=F])

ASV21plot=ggplot(ASV21, aes(x=paste0("20", Year),fill=BM,  y=100*(ASV21)/19355))+
 geom_errorbar(
       size=2, stat="summary", position = 
position_dodge2(width = 1))+
  geom_bar(
       size=2, stat="summary", position = 
position_dodge2(width = 1))+
  theme_bw() +
  xlab("Year")+ ylab(expression(bold(paste("ASV21 RA%"))))+
  
  theme( axis.text.y = element_text( size=40, face = "bold", colour="black")) +
  theme(axis.text.x = element_text(size = 40, face = "bold", colour="black")) +
  theme(legend.text = element_text( size=40, face="bold", colour = "black")) + 
  theme( axis.title.y = element_text( size=40, face = "bold", colour="black")) + 
  theme(axis.title.x = element_text(size = 40, face = "bold", colour="black")) +
  theme(legend.title =  element_text( size=40, face="bold", colour = "black"))+
  theme(plot.title =  element_text( size=40, face="bold", colour = "black"))+
  
  theme( strip.text = element_text( size=40, face = "bold.italic", colour="black")) +
  theme( strip.background = element_rect( fill="white", colour = "white")) +
  theme(legend.position="right") + theme( axis.line = element_line(colour = "black", 
                                                                   size = 1.5, linetype = "solid"))+ 
  stat_compare_means(method = "wilcox.test", label = "p.signif",size=10, hide.ns = T)+
    scale_fill_manual(name="",values=c( "#ff9900","#146eb4"))+ylim(0,3.2)

```

}


```



