```{r}
library(tidyverse)
library(ggplot2)
library(plyr)
library(dplyr)
library(readr)
library(readxl)
library(ggpubr)
library(stringi)
library(tidyr)
library(reshape2)
library(vegan)
library(phyloseq)
library(decontam)
```


```{r}
ASVtable1= read.csv("ASV_Table_LTE_three_years.csv")
metadata= data.frame(Sample=colnames(ASVtable1[,15:(ncol(ASVtable1)-1)]), 
ID=colnames(ASVtable1[,15:(ncol(ASVtable1)-1)]))%>%
  mutate(Sample=str_replace(Sample,".trimmed",""))%>%
  mutate(Sample=str_replace(Sample,".trimmed",""))%>%
  separate(Sample, into = c("Sample", "Year"), sep = "..20" )%>%
  mutate(Time_point= str_replace(Sample, ".*.T0.*.","T0"))%>%
  mutate(Soil_Type= str_replace(Sample, ".*.T0.*.","FS_T0"))%>%
  
  mutate(Soil_Type= str_replace(Soil_Type, "FS.*.","FS"))%>%
  mutate(Soil_Type= str_replace(Soil_Type, "RH.*","RH"))%>%
  mutate(Tillage= str_replace(Sample, ".*CT.*.","CT"))%>%
  mutate(Tillage= str_replace(Tillage, ".*MP.*.","MP"))%>%
  mutate(Int= str_replace(Sample, ".*In.*.","Intensive"))%>%
  mutate(Int= str_replace(Int, ".*Ex.*.","Extensive"))%>%
  mutate(BMc= str_replace(Sample, ".*.t.I.*","BMc"))%>%
  mutate(BMc= str_replace(BMc, ".*.x.I.*","BMc"))%>%
  mutate(BMc= str_replace(BMc, ".*.n.I.*","BMc"))%>%
  mutate(Int= str_replace(Int, ".*Ex.*.","Extensive"))%>%
  mutate(Block=str_sub(Sample, -1, -1)  )%>% 
  mutate(Root_Window=str_replace(Sample, ".*.RW.*.","RW"))
metadata$BMc[metadata$BMc!="BMc"]<-"Ctrl"
metadata$Block=as.numeric(metadata$Block)
metadata$Root_Window[metadata$Root_Window!="RW"]<-"Normal-Sample"
```  
```{r}
metadata1=filter(metadata,
                 Year%in%c(20,21,22)&Tillage=="CT"|Sample%in%c(
"Neg","DNAextContrlAp13rdphas",
"lypthconDNAextContrlAp13rdphas"
                 ))
```
```{r}
metadata2=filter(metadata1,
Year%in%c(20,21,22)&Tillage=="CT"&Int=="Extensive"
                 )
```

```{r}
metadata2=metadata1

ASVtable_clean=ASVtable1[,metadata2$ID]
depth1=data.frame( colSums(ASVtable_clean[,metadata2$ID]))
colnames(depth1)="Depth"
densityplot(depth1$Depth)          
depth2=filter(depth1, Depth>18000)
library(parallel)
```
```{r}
quickRareCurve <- function (x, step = 1, sample, xlab = "Sample Size",
                            ylab = "Species", label = TRUE, col, lty, max.cores = T, nCores = 20, ...)
{
  require(parallel)
  x <- as.matrix(x)
  if (!identical(all.equal(x, round(x)), TRUE))
    stop("function accepts only integers (counts)")
  if (missing(col))
    col <- par("col")
  if (missing(lty))
    lty <- par("lty")
  tot <- rowSums(x) # calculates library sizes
  S <- specnumber(x) # calculates n species for each sample
  if (any(S <= 0)) {
    message("empty rows removed")
    x <- x[S > 0, , drop = FALSE]
    tot <- tot[S > 0]
    S <- S[S > 0]
  } # removes any empty rows
  nr <- nrow(x) # number of samples
  col <- rep(col, length.out = nr)
  lty <- rep(lty, length.out = nr)
  # parallel mclapply
  # set number of cores
  mc <- getOption("mc.cores", ifelse(max.cores, detectCores(), nCores))
  message(paste("Using ", mc/3, " cores"))
  out <- mclapply(seq_len(nr), mc.cores = mc/3, function(i) {
    n <- seq(1, tot[i], by = step)
    if (n[length(n)] != tot[i])
      n <- c(n, tot[i])
    drop(rarefy(x[i, ], n))
  })
  Nmax <- sapply(out, function(x) max(attr(x, "Subsample")))
  Smax <- sapply(out, max)
  plot(c(1, max(Nmax)), c(1, max(Smax)), xlab = xlab, ylab = ylab,
       type = "n", ...)
  if (!missing(sample)) {
    abline(v = sample)
    rare <- sapply(out, function(z) approx(x = attr(z, "Subsample"),
                                           y = z, xout = sample, rule = 1)$y)
    abline(h = rare, lwd = 0.5)
  }
  for (ln in seq_along(out)) {
    N <- attr(out[[ln]], "Subsample")
    lines(N, out[[ln]], col = col[ln], lty = lty[ln], ...)
  }
  if (label) {
    ordilabel(cbind(tot, S), labels = rownames(x), ...)
  }
  invisible(out)
}


rarefaction_curve=  quickRareCurve(t(ASVtable_clean))  
names(rarefaction_curve) <- paste("Sample", 1:ncol(ASVtable_clean), sep = "")
# Coerce data into "long" form.
protox <- mapply(FUN = function(x, y) {
  mydf <- as.data.frame(x)
  colnames(mydf) <- "value"
  mydf$species <- y
  mydf$subsample <- attr(x, "Subsample")
  mydf
}, x = rarefaction_curve, y = as.list(names(rarefaction_curve)), SIMPLIFY = FALSE)

xy <- do.call(rbind, protox)
rownames(xy) <- NULL  # pretty



# Plot the rarefaction curve.
rarecurve_plot= ggplot(xy, aes(x = subsample, y = value, color = species)) +
  theme_bw() +
  scale_color_discrete(guide = "none") +  # turn legend on or off
  geom_line() + ylab("ASV Richness")+xlab("Sequencing Depth")
rarecurve_plot

pdf(  "rarecurve.pdf", width = 1000, height = 1000)
print(rarecurve_plot)
dev.off()
```

```{r}
#Alpha Diversity Metrics
#First set the functions
Species.richness <- function(x)
{
  # Count  the OTUs that are present >0 normalized counts (normalization produces real values for counts)
  count=sum(x[x>0]^0)
  return(count)
}
```

```{r}
minimum_seq=min(depth2)

Have_you_Runned_previously_RF<-"NO"
if (Have_you_Runned_previously_RF=="NO"){
  list_of_1000_rarefaction=mclapply(1:1000, function(i){ rrarefy(t(ASVtable_clean[,rownames(depth2)]), minimum_seq)},
                                    mc.cores = 10)
  
  df= as.data.frame( list_of_1000_rarefaction[[1]])
   richness1=as.data.frame( apply(df, 1, function(x) Species.richness(x)))
   shannon1=as.data.frame( diversity( df, index = "shannon"))
   simpson1=as.data.frame( diversity(  df, index = "invsimpson"))
   fisher.alpha1=fisher.alpha(df, MARGIN = 1)

   
   for (i in 2:1000){
    df=df+list_of_1000_rarefaction[[i]]
    print(i)
    richness1=richness1+as.data.frame( apply(list_of_1000_rarefaction[[i]], 1, function(x) Species.richness(x)))
    shannon1=shannon1+as.data.frame(  diversity(list_of_1000_rarefaction[[i]], index = "shannon"))
    simpson1=simpson1+as.data.frame( diversity( list_of_1000_rarefaction[[i]], index = "invsimpson"))
    fisher.alpha1=fisher.alpha1+fisher.alpha(list_of_1000_rarefaction[[i]], MARGIN = 1)
      
    }
   
   Rarefied_Table=df/1000
   Rarefied_Richness=richness1/1000
   Rarefied_Shannon=shannon1/1000
   Rarefied_simpson=simpson1/1000
   Rarefied_fisher=fisher.alpha1/1000

  
  
}

write.csv(Rarefied_Table,file = "3yearsRarefied_table.csv")
write.csv(Rarefied_Richness,file = "3yearsGERarefied_Richness.csv")
write.csv(Rarefied_Shannon,file = "3yearsRarefied_Shannon.csv")
write.csv(Rarefied_fisher,file = "3yearsRarefied_fisher.csv")
write.csv(Rarefied_simpson,file = "3yearsRarefied_simpson.csv")
```