---
title: "Plant biomass, MS5"
author: "Ioannis D. Kampouris"
date: "2025-02-11"
output: pdf_document
---
Load the packages
```{r}
library(tidyverse)
library(ggplot2)
library(plyr)
library(dplyr)
library(readr)
library(readxl)
library(ggpubr)
library(stringi)
library(tidyr)
library(reshape2)
library(vegan)
library(parallel)
```
Load the metadata
```{r}
metadata1=read.csv("metadata1.csv")
biomass1=read_excel("Growth_Data_for_LTEs.xlsx")
Nutrients=read_excel("Nutrients_20_21_22.xlsx")
```

```{r}
Shoot_DW_plot= ggplot(biomass1, 
aes(y=Shoot_DW, x=as.factor(paste0("20", Year)),
    fill=BENEFICIALS))+ geom_errorbar(
       size=2, stat="summary", position = 
position_dodge2(width = 1))+
  geom_bar(
       size=2, stat="summary", position = 
position_dodge2(width = 1))+
  theme_bw() +
  xlab("Year")+ ylab(expression(bold(paste("g "~"plant"^{-1}))))+
  
  theme( axis.text.y = element_text( size=40, face = "bold", colour="black")) +
  theme(axis.text.x = element_text(size = 40, face = "bold", colour="black")) +
  theme(legend.text = element_text( size=40, face="bold", colour = "black")) + 
  theme( axis.title.y = element_text( size=40, face = "bold", colour="black")) + 
  theme(axis.title.x = element_text(size = 40, face = "bold", colour="black")) +
  theme(legend.title =  element_text( size=40, face="bold", colour = "black"))+
  theme(plot.title =  element_text( size=40, face="bold", colour = "black"))+
  
  theme( strip.text = element_text( size=40, face = "bold.italic", colour="black")) +
  theme( strip.background = element_rect( fill="white", colour = "white")) +
  theme(legend.position="right") + theme( axis.line = element_line(colour = "black", 
                                                                   size = 1.5, linetype = "solid"))+ 
  stat_compare_means(method = "wilcox.test", label = "p.signif",size=10, hide.ns = T)+
    scale_fill_manual(name="",values=c( "#ff9900","#146eb4"))

```


```{r}
ggsave(Shoot_DW_plot,file ="3yearsSDM_plot.pdf",  height = 8, width = 16)
```

```{r}
Nutrients=read_excel("Nutrients_20_21_22.xlsx")
NutrientsDistance=vegdist( scale(Nutrients[,12:20]), method = "euclidean")
NutrientsDistance2=cmdscale(NutrientsDistance, eig = T, k=2)
NutrientsDistance3=scores(NutrientsDistance2, display = "sites")
NutrientsDistance4=cbind(NutrientsDistance3, Nutrients)
```

```{r}
Nutrient_Plot=ggplot(NutrientsDistance4, aes(x=Dim1, y=Dim2, shape=as.factor(Year), fill=BMc))+
  geom_point(colour="black", size=10)+scale_shape_manual(values =c(21,22,23) )

```


```{r}
Nutrients2=gather(Nutrients, -c(colnames(Nutrients[,1:11])),
                  key="Nutrient", value="Value")

Nutrient_Plot=ggplot(Nutrients, aes(x=as.factor(Year), y=`Fe[mg/kg]`, fill=BMc))+
  geom_boxplot()

Fe_plot= ggplot(Nutrients2, 
aes(y=Nutrient, x=as.factor(paste0("20", Year)),
    fill=BMc))+ geom_errorbar(
       size=2, stat="summary", position = 
position_dodge2(width = 1))+
  geom_bar(
       size=2, stat="summary", position = 
position_dodge2(width = 1))+
  theme_bw() +
  xlab("Year")+
  
  theme( axis.text.y = element_text( size=0, face = "bold", colour="black")) +
  theme(axis.text.x = element_text(size = 40, face = "bold", colour="black")) +
  theme(legend.text = element_text( size=40, face="bold", colour = "black")) + 
  theme( axis.title.y = element_text( size=40, face = "bold", colour="black")) + 
  theme(axis.title.x = element_text(size = 40, face = "bold", colour="black")) +
  theme(legend.title =  element_text( size=40, face="bold", colour = "black"))+
  theme(plot.title =  element_text( size=40, face="bold", colour = "black"))+
  
  theme( strip.text = element_text( size=40, face = "bold.italic", colour="black")) +
  theme( strip.background = element_rect( fill="white", colour = "white")) +
  theme(legend.position="right") + theme( axis.line = element_line(colour = "black", 
                                                                   size = 1.5, linetype = "solid"))+ 
  stat_compare_means(method = "wilcox.test", label = "p.signif",size=10, hide.ns = T)+
    scale_fill_manual(name="",values=c( "#ff9900","#146eb4"))


```
```{r}
new_with_letters=list()
for(i in unique(paste0(Nutrients2$Nutrient))){
file1=filter(Nutrients2, Nutrient==paste0(i)) 
file1$G=paste0(file1$BMc,"_",file1$Year)
dunns= aov(file1$Value~file1$G)
comparisons=data.frame(comparisons=dunns$comparisons, p=dunns$P.adjusted)%>%
  separate(., "comparisons", into = c("row","col"), sep = " - ")
orderlist= aggregate( file1, Value~G, max)
comparisons=full_join(comparisons, orderlist%>%mutate(row=G), by="row")%>%na.omit()
comparisons=comparisons[order(comparisons$Value, decreasing = T),]
names1=paste0(comparisons$row,"-", comparisons$col)
p=comparisons$p
names(p)=names1
letters=  multcompView::multcompLetters(p,  compare = "<", reversed =F)$Letters%>%as.data.frame()

colnames(letters)="L1"
letters$G=rownames(letters)
file1=full_join(file1,letters)
new_with_letters=rbind(new_with_letters,file1)
}
```

```{r}

new_with_letters$Nutrient=factor(
  new_with_letters$Nutrient,
  levels = c( 
"Ca[g/kg]",
 "K[g/kg]",
"Mg[g/kg]", 
"P[g/kg]",   
"S[g/kg]",
"Cu[mg/kg]", 
"Fe[mg/kg]",
"Mn[mg/kg]",
"Zn[mg/kg]"),

  labels = c( expression(paste("Ca g ", kg^{-1}, "")),
              expression(paste("K  g ", kg^{-1}, "")),
              expression(paste("Mg g ", kg^{-1}, "")),
              expression(paste("P g ", kg^{-1}, "")),
              expression(paste("S g ", kg^{-1}, "")),
              expression(paste("Cu mg ", kg^{-1}, "")), 
              expression(paste("Fe mg ", lg^{-1}, "")),
              expression(paste("Mn mg ", kg^{-1}, "")),
              expression(paste("Zn mg ", kg^{-1}, ""))))


plot_nutri =ggplot(Nutrients3, 
  aes(y=Value, x=as.factor(paste0("20",Year)), fill=BMc)) +
  geom_pointrange(shape=21, stat="summary",
                  size=2.5, position = position_dodge2(width = 1) ) +
  facet_wrap(~Nutrient,  nrow=2, scales = "free", labeller = label_parsed,
             strip.position = "left") +
  scale_fill_manual(name="",values=c( "#ff9900","#146eb4"))+
  theme_bw() +
  theme(axis.text.y=element_text(size=25, colour="black")) +
  theme(strip.background=element_rect(fill="white", colour="white"),
        strip.placement = "left") +
  theme(strip.text=element_text(colour="black", size=25)) +
  theme(axis.text.x=element_text(size=25, colour="black")) +
  theme(legend.text=element_text(size=25, colour="black")) + 
  theme(legend.title=element_text(size=25, colour="black")) + 
  theme(legend.position="top", axis.title.y=element_text(size=25,  colour="black")) + 
  theme(axis.title.x=element_text(size=25, colour="black")) +
  theme(legend.key.size=unit(2,"cm")) +
  ylab("") +
  xlab("") + stat_pwc(label = "p.signif", hide.ns = T)


iron_nutri =ggplot(Nutrients, 
  aes(y=`Fe[mg/kg]`, x=as.factor(paste0("20",Year)), fill=BMc)) +
  geom_pointrange(shape=21, stat="summary",
                  size=2.5, position = position_dodge2(width = 1) ) +

  scale_fill_manual(name="",values=c( "#ff9900","#146eb4"))+
  theme_bw() +
  theme(axis.text.y=element_text(size=25, colour="black")) +
  theme(strip.background=element_rect(fill="white", colour="white"),
        strip.placement = "left") +
  theme(strip.text=element_text(colour="black", size=25)) +
  theme(axis.text.x=element_text(size=25, colour="black")) +
  theme(legend.text=element_text(size=25, colour="black")) + 
  theme(legend.title=element_text(size=25, colour="black")) + 
  theme(legend.position="top", axis.title.y=element_text(size=25,  colour="black")) + 
  theme(axis.title.x=element_text(size=25, colour="black")) +
  theme(legend.key.size=unit(2,"cm")) +
  ylab(expression(paste("Fe mg ", kg^{-1}, ))) +
  xlab("")+ stat_pwc(label = "p.signif", hide.ns = T, label.size=10)
```
