---
title: "MAG_functional_genes"
author: "Theresa Kuhl-Nagel"
date: "2025-09-13"
output: html_document
---

```{r}
library(ggplot2)
library(patchwork)
MAG <- read.table("~/Data/Backmapping_selected_MAGs_R.txt", header=T, sep="\t", dec=".") 
head(MAG)
```
```{r}
MAG$Bacillus.atrophaeus_percent <- (MAG$Bacillus.atrophaeus / MAG$Total) * 100
MAG$Lysobacter.antibioticus_percent <- (MAG$Lysobacter.antibioticus / MAG$Total) * 100
```

```{r}
library(tidyr)
df_long <- pivot_longer(MAG, 
                        cols = c(Bacillus.atrophaeus_percent, Lysobacter.antibioticus_percent), 
                        names_to = "Genome", 
                        values_to = "Percentage")
```

```{r}
library(ggplot2)
p1 <- ggplot(df_long, aes(x = Gene, y = Percentage, fill = Genome)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  ylab("Percentage (%)") +
  #xlab("Gene") +
  scale_fill_manual(values = c("grey60", "grey80"),
                  labels = c(expression(italic("B. atrophaeus")), expression(italic("L. antibioticus"))))+
  scale_y_continuous(expand = expansion(mult = c(0, 0)), limits = c(0, 100))+
  theme_minimal()+
  theme(
    axis.text.x = element_text(face = "italic", size = 10, angle = 45, hjust = 1),
    axis.text.y = element_text(size = 10),
    axis.title.y = element_text(size = 10),
    axis.title.x = element_blank(),
    panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
    panel.border = element_blank(),       
    axis.line = element_line(color = "grey40", size = 0.5),
    legend.position = "bottom",
    legend.title = element_blank(),
    legend.text = element_text(size = 10)
  )
p1
```
```{r, fig.width=12, fig.height=7}
library(cowplot)
plot_grid(combined, p1, nrow = 1, rel_widths = c(2.5, 1))
```



