---
title: "CT202122_statistics_ordination"
author: "Theresa Kuhl-Nagel"
date: "2024-06-24"
output: html_document
---
```{r}
library(agricolae)
library(vegan)
library(phyloseq)
library(RColorBrewer)
library(ggplot2)
library(ellipse)
library(writexl)
library(DESeq2)
```

Load data
```{r}
CDB <- read.csv("~/Data/CTExt2022122_bacteria_Plabase_anno_sum.csv", row.names = 1)#, 
dim(CDB)
head(CDB)

metadat <- read.table("~/Data/Metadata_CTExt202122.txt", header=T, sep="\t", dec=".",  row.names = 1) 
head(metadat)
```

#Subset data for years
2020
```{r}
metadat_2020 <- metadat_minor[metadat_minor$Year == "2020", ]
count_data_2020 <- tCDB_minor[, rownames(metadat_2020)]

# Create DESeqDataSet for Year 2020 (only treatment effect)
dds_2020 <- DESeqDataSetFromMatrix(countData = count_data_2020, 
                                    colData = metadat_2020, 
                                    design = ~ Beneficials)  # Design formula with treatment

# Run DESeq2 for Year 2020
dds_2020 <- DESeq(dds_2020)
res_2020 <- results(dds_2020)
summary(res_2020)

# Filter for significant results (padj < 0.05, for example)
res_2020_sig <- res_2020[which(res_2020$padj < 0.05), ]
print(res_2020_sig)
#log2 fold change (MLE): Beneficials Control vs BMc 
#Wald test p-value: Beneficials Control vs BMc 
#DataFrame with 21 rows and 6 columns
```
2021
```{r}
metadat_2021 <- metadat_minor[metadat_minor$Year == "2021", ]
count_data_2021 <- tCDB_minor[, rownames(metadat_2021)]

# Create DESeqDataSet for Year 2020 (only treatment effect)
dds_2021 <- DESeqDataSetFromMatrix(countData = count_data_2021, 
                                    colData = metadat_2021, 
                                    design = ~ Beneficials)  # Design formula with treatment

# Run DESeq2 for Year 2020
dds_2021 <- DESeq(dds_2021)
res_2021 <- results(dds_2021)
summary(res_2021)

# Filter for significant results (padj < 0.05, for example)
res_2021_sig <- res_2021[which(res_2021$padj < 0.05), ]
print(res_2021_sig)
#log2 fold change (MLE): Beneficials Control vs BMc 
#Wald test p-value: Beneficials Control vs BMc 
#DataFrame with 9 rows and 6 columns
```

2022
```{r}
metadat_2022 <- metadat_minor[metadat_minor$Year == "2022", ]
count_data_2022 <- tCDB_minor[, rownames(metadat_2022)]

# Create DESeqDataSet for Year 2020 (only treatment effect)
dds_2022 <- DESeqDataSetFromMatrix(countData = count_data_2022, 
                                    colData = metadat_2022, 
                                    design = ~ Beneficials)  # Design formula with treatment

# Run DESeq2 for Year 2022
dds_2022 <- DESeq(dds_2022)
res_2022 <- results(dds_2022)
summary(res_2022)

# Filter for significant results (padj < 0.05, for example)
res_2022_sig <- res_2022[which(res_2022$padj < 0.05), ]
print(res_2022_sig)
#log2 fold change (MLE): Beneficials Control vs BMc 
#Wald test p-value: Beneficials Control vs BMc 
#DataFrame with 0 rows and 6 columns
```

